[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:code-server]
command=/usr/bin/code-server --bind-addr 127.0.0.1:8081 --auth none /workspace
environment=HOME="/workspace",USER="superuser"
directory=/workspace
autostart=true
autorestart=true

[program:ttyd]
command=/usr/local/bin/ttyd -t title="Workbench" -t bellStyle=sound -T xterm-256color -W -p 8082 zellij --layout /etc/workbench/zellij-layout.kdl attach -c Workbench
environment=HOME="/workspace",USER="superuser",TERM="xterm-256color"
directory=/workspace
autostart=true
autorestart=true

[program:caddy]
command=/usr/bin/caddy run --config /etc/workbench/Caddyfile
environment=HOME="/workspace",USER="superuser"
directory=/workspace
autostart=true
autorestart=true

[program:autoinstall]
command=/usr/local/bin/workbench/run-autoinstall.sh
environment=HOME="/workspace",USER="superuser"
directory=/workspace
autostart=true
autorestart=false
startretries=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
